"""initial schema

Revision ID: b5834ca8968c
Revises: 
Create Date: 2026-08-11 21:22:07.190510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5834ca8968c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('habit_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('habit_name', sa.String(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('habit_id')
    )
    op.create_table('prediction_logs',
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('habit_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.habit_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('habit_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('habit_id', sa.String(), nullable=False),
    sa.Column('prediction_log_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('meals_eaten', sa.Integer(), nullable=False),
    sa.Column('workload_hours', sa.Float(), nullable=False),
    sa.Column('habit_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('interruptions', sa.Integer(), nullable=False),
    sa.Column('medication', sa.Boolean(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('completed_yesterday', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.habit_id'], ),
    sa.ForeignKeyConstraint(['prediction_log_id'], ['prediction_logs.prediction_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_logs')
    op.drop_table('prediction_logs')
    op.drop_table('habits')
    # ### end Alembic commands ###
